source "https://rubygems.org"

group :test do
  gem "rake", "~> 10.0"
  if puppet_gem_version = ENV['PUPPET_GEM_VERSION']
    gem "puppet", ENV['PUPPET_GEM_VERSION']
  elsif puppet_git_url = ENV['PUPPET_GIT_URL']
    gem "puppet", :git => "#{puppet_git_url}"
  else
    gem "puppet", ENV['PUPPET_GEM_VERSION']
  end
  gem "puppet-lint"
  gem "puppet-lint-unquoted_string-check"
  gem "rspec-puppet"
  gem "puppet-syntax"
  gem "puppetlabs_spec_helper"
  gem "metadata-json-lint"
  gem "rspec"
  gem "rspec-retry"
  gem 'simplecov', '>= 0.11.0'
  gem 'simplecov-console'
end

